"use client";

import { Suspense, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { getAudit } from "@workspace/api-client-react";
import type { AuditResult } from "@workspace/api-client-react";
import { AutoPrint } from "@/components/reports/auto-print";
import { ReportPrintToolbar } from "@/components/reports/report-print-toolbar";
import { POUR_PRINCIPLES } from "@/data/pour-principles";
import { groupViolationsByPour } from "@/lib/pour-mapper";
import { difficultyLabel, getFixDifficulty } from "@/lib/a11y-fix";
import { auditRowIsPending, auditRowLooksUsable } from "@/lib/audit-row-status";

function A11yFixReportPrintInner() {
  const params = useParams();
  const auditId = typeof params?.auditId === "string" ? params.auditId : "";
  const [audit, setAudit] = useState<AuditResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!auditId) {
      setError("Missing audit ID.");
      return;
    }

    let cancelled = false;
    let attempts = 0;

    const load = async () => {
      try {
        const row = await getAudit(auditId);
        if (cancelled) return;
        if (auditRowLooksUsable(row)) {
          setAudit(row);
          return;
        }
        if (auditRowIsPending(row) && attempts < 120) {
          attempts += 1;
          window.setTimeout(load, 1000);
          return;
        }
        setAudit(row);
      } catch {
        if (!cancelled) setError("Could not load audit data for this report.");
      }
    };

    void load();
    return () => {
      cancelled = true;
    };
  }, [auditId]);

  if (error) {
    return <p className="p-8 text-sm text-destructive">{error}</p>;
  }

  if (!audit) {
    return <p className="p-8 text-sm text-muted-foreground">Loading report…</p>;
  }

  const violations = Array.isArray(audit.violations) ? audit.violations : [];
  const pourGroups = groupViolationsByPour(violations);
  const scannedDate = new Date(audit.scannedAt).toLocaleString("en-GB", {
    dateStyle: "long",
    timeStyle: "short",
  });

  return (
    <>
      <AutoPrint />
      <ReportPrintToolbar title="A11y Fix report (POUR)" />
      <article className="report-document mx-auto max-w-[210mm] bg-white px-8 py-10 text-[11pt] print:px-0 print:py-0">
        <header className="mb-8 rounded-lg bg-[#1a1a1a] px-6 py-5 text-white print:rounded-none">
          <p className="text-lg font-bold">A11y Fix</p>
          <p className="mt-1 text-xs text-white/60">BITV 2.0 / BFSG · POUR-grouped fix plan</p>
          <p className="mt-1 text-xs text-[#FF4D1C]">accessibility.now</p>
        </header>

        <section className="mb-6 border-b border-border pb-4 text-sm">
          <p className="break-all font-semibold">{audit.url}</p>
          <p className="text-xs text-muted-foreground">Scanned {scannedDate}</p>
          <p className="mt-3 text-3xl font-extrabold tabular-nums">{audit.score}</p>
          <p className="text-xs text-muted-foreground">
            {audit.criticalViolations} critical · {audit.seriousViolations} serious · {audit.totalViolations} total
          </p>
        </section>

        {POUR_PRINCIPLES.map((p) => {
          const items = pourGroups[p.name] ?? [];
          if (items.length === 0) return null;
          return (
            <section key={p.name} className="mb-6 break-inside-avoid">
              <h2 className={`mb-2 border-b border-border pb-1 text-sm font-bold ${p.color}`}>{p.name}</h2>
              <ol className="space-y-3">
                {items.slice(0, 8).map((v, i) => (
                  <li key={`${v.id}-${i}`} className="text-sm">
                    <p className="font-semibold">{v.description}</p>
                    <p className="text-xs text-muted-foreground">
                      {v.wcagCriteria} · {difficultyLabel(getFixDifficulty(v.id))} fix
                    </p>
                  </li>
                ))}
              </ol>
            </section>
          );
        })}

        <footer className="mt-8 border-t border-border pt-4 text-[10px] text-muted-foreground">
          <p>Generated by accessibility.now A11y Fix · Audit ID: {audit.auditId}</p>
        </footer>
      </article>
    </>
  );
}

export default function A11yFixReportPrintPage() {
  return (
    <Suspense fallback={<p className="p-8 text-sm text-muted-foreground">Loading…</p>}>
      <A11yFixReportPrintInner />
    </Suspense>
  );
}
